// webpack // webpack cli 


// javascript dom ... document.getlem ajax 




var webpack = require('webpack');
var path = require('path');

module.exports = {

// debugging easier , which files has error
devtool:'inline-source-map', // eval-source-map

entry:{
	'index':'./src/index.js'
},

output:{ // path.resolve path.join 
	//resolve absolute path
	path: path.resolve(__dirname,'dist'),
	filename:'main.js'
},

module:{
	rules: [ 
		{ 
				
			test:/\.js$/, 
			exclude:/node_modules/,
			use: 'babel-loader'


		},
		//for css files
		{
			test:/\.css$/,

			use:['style-loader','css-loader'] 

		}

	]
},


devServer:{

// those content that are not generated by webpack
	contentBase: path.join(__dirname,"public/"),
	port:3000,
	// to serve webpack files 
	
	hot:true,
    publicPath: "http://localhost:3000/dist/"

}

}
